/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.boilerplates;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ExecutionException;

public class App {

  public String getGreeting() {
    return "Hello world.";
  }

  public static void main(String[] args) throws InterruptedException, ExecutionException {
        //System.out.println(new App().getGreeting());
        System.out.println("---------- ---------- SimpleFuture ---------- ----------");
        SimpleFuture simpleFuture = new SimpleFuture();
        simpleFuture.run();
        simpleFuture.close();
        Thread.sleep(3000);
        System.out.println("---------- ---------- RxExamples ---------- ----------");
        RxExamples.helloWorld();
        RxExamples.observableFromList();
        RxExamples.concurrency();
        RxExamples.parallel();
        Thread.sleep(3000);
        System.out.println("---------- ---------- RxFuture ---------- ----------");
        RxFuture rxFuture = new RxFuture();
        rxFuture.run();
        rxFuture.close();
        Thread.sleep(3000);
        System.out.println("---------- ---------- Wikipedia ---------- ----------");
        final  List<String> x = new ArrayList<>(Arrays.asList("Home", "sdfsrbdf","House"));
        Wikipedia.createObservable(x);
    }
    
}
