# -----------------------------------------------------------------------------
# CMake project wrapper Makefile ----------------------------------------------
# -----------------------------------------------------------------------------
# Remember to use TAB before commands!!!!!!!
# http://mrbook.org/blog/tutorials/make/
all:
	cmake -H. -Bbuild 
	cd build && make

run:
	./build/hello_world
